"use client";

import { useEffect, useState, useRef } from "react";
import { Play, RotateCcw, StopCircle, Copy, Check, Loader2, Download, ShieldAlert } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { SurvivalChart } from "./survival-chart";

const V2_CODE_TEMPLATE = `# Generated by AI Co-Scientist
import pandas as pd
from lifelines import KaplanMeierFitter

# 1. Load Data
df = load_cohort('current_selection')
group_3 = df[df['stage'] == 'III']
group_4 = df[df['stage'] == 'IV']

# 2. Statistical Test (T-test)
from scipy import stats
t_stat, p_val = stats.ttest_ind(group_3['hrd_score'], group_4['hrd_score'])
print(f"P-value: {p_val:.4f}")

# 3. Plot Survival
kmf = KaplanMeierFitter()
kmf.fit(group_3['time'], group_3['event'], label='Stage III')
ax = kmf.plot()
kmf.fit(group_4['time'], group_4['event'], label='Stage IV')
kmf.plot(ax=ax)`;

interface NotebookPanelProps {
    isRunning: boolean;
    onRunComplete: () => void;
}

export function NotebookPanel({ isRunning, onRunComplete }: NotebookPanelProps) {
    const [displayedCode, setDisplayedCode] = useState("");
    const [isCopied, setIsCopied] = useState(false);
    const [showOutput, setShowOutput] = useState(false);
    const [isExecuting, setIsExecuting] = useState(false);
    const [showPIIToast, setShowPIIToast] = useState(false);

    // Typewriter effect
    useEffect(() => {
        if (isRunning) {
            setDisplayedCode("");
            setShowOutput(false);
            setIsExecuting(false);

            let i = 0;
            const interval = setInterval(() => {
                setDisplayedCode(V2_CODE_TEMPLATE.slice(0, i));
                i++;
                if (i > V2_CODE_TEMPLATE.length) {
                    clearInterval(interval);
                    setIsExecuting(true); // Start execution spinner
                    setTimeout(() => {
                        setIsExecuting(false);
                        setShowOutput(true);
                        onRunComplete();
                    }, 1500); // 1.5s execution delay
                }
            }, 5); // Faster typing speed for v2

            return () => clearInterval(interval);
        }
    }, [isRunning, onRunComplete]);

    const handleCopy = () => {
        navigator.clipboard.writeText(V2_CODE_TEMPLATE);
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
    };

    const handleExport = () => {
        setShowPIIToast(true);
        setTimeout(() => setShowPIIToast(false), 3000);
    };

    return (
        <div className="flex flex-col h-full bg-slate-50 border-l border-gray-200 relative">
            {/* PII Toast */}
            <AnimatePresence>
                {showPIIToast && (
                    <motion.div
                        initial={{ opacity: 0, y: -20, x: "-50%" }}
                        animate={{ opacity: 1, y: 0, x: "-50%" }}
                        exit={{ opacity: 0, y: -20, x: "-50%" }}
                        className="absolute top-16 left-1/2 flex items-center gap-3 px-4 py-3 bg-slate-900/90 text-white rounded-lg shadow-xl z-50 backdrop-blur-sm"
                    >
                        <ShieldAlert className="w-5 h-5 text-amber-500" />
                        <div>
                            <p className="text-sm font-medium">AI scanning for PII...</p>
                            <p className="text-xs text-slate-300">Export pending security clearance.</p>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Toolbar */}
            <div className="flex items-center justify-between px-4 py-2 bg-white border-b border-gray-200 shadow-sm z-10">
                <div className="flex items-center gap-2">
                    <button className="p-1.5 hover:bg-emerald-50 text-slate-500 hover:text-emerald-600 rounded transition-colors" title="Run">
                        <Play className="w-4 h-4 fill-current" />
                    </button>
                    <button className="p-1.5 hover:bg-red-50 text-slate-500 hover:text-red-600 rounded transition-colors" title="Stop">
                        <StopCircle className="w-4 h-4" />
                    </button>
                    <button className="p-1.5 hover:bg-slate-100 text-slate-500 hover:text-slate-900 rounded transition-colors" title="Restart Kernel">
                        <RotateCcw className="w-4 h-4" />
                    </button>
                    <div className="w-px h-4 bg-gray-300 mx-1" />
                    <button
                        onClick={handleExport}
                        className="p-1.5 hover:bg-indigo-50 text-slate-500 hover:text-indigo-600 rounded transition-colors"
                        title="Export Notebook"
                    >
                        <Download className="w-4 h-4" />
                    </button>
                </div>
                <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-400">Python 3 (ipykernel)</span>
                    <div className={cn("w-2 h-2 rounded-full", isRunning || isExecuting ? "bg-emerald-500 animate-pulse" : "bg-slate-300")} />
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-sm">
                {/* Code Cell */}
                <div className="group relative">
                    <div className="absolute -left-8 top-1 text-xs text-slate-400 font-mono">
                        In [{isRunning || isExecuting ? "*" : "1"}]:
                    </div>

                    <div className="border border-gray-300 rounded-md bg-white shadow-sm overflow-hidden focus-within:ring-2 focus-within:ring-indigo-500 focus-within:border-transparent transition-all">
                        <div
                            className="p-4 bg-white text-slate-800 leading-relaxed overflow-x-auto outline-none"
                            contentEditable
                            suppressContentEditableWarning
                        >
                            <pre style={{ whiteSpace: "pre-wrap" }}>
                                {displayedCode}
                                {isRunning && <span className="inline-block w-2 h-4 bg-slate-500 ml-1 animate-pulse" />}
                            </pre>
                            {!displayedCode && !isRunning && (
                                <div className="text-slate-300 italic select-none"># AI Agent is ready to code...</div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Output Cell */}
                {(showOutput || isExecuting) && (
                    <div className="group relative">
                        <div className="absolute -left-8 top-1 text-xs text-red-500 font-mono">
                            Out[1]:
                        </div>
                        {isExecuting && (
                            <div className="flex items-center gap-2 text-slate-500 italic p-2">
                                <Loader2 className="w-4 h-4 animate-spin" />
                                Running Statistical Test...
                            </div>
                        )}
                        {showOutput && (
                            <motion.div
                                initial={{ opacity: 0, y: 5 }}
                                animate={{ opacity: 1, y: 0 }}
                                className="space-y-4 pl-1"
                            >
                                <div className="font-mono text-xs text-slate-700">
                                    P-value: 0.0042
                                </div>
                                <div className="border border-gray-200 rounded-lg bg-white p-4 shadow-sm h-[400px]">
                                    <SurvivalChart />
                                </div>
                            </motion.div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
