export type Patient = {
    id: string;
    type: string;
    stage: string;
    hrd: number;
    os_months: number;
    status: "Alive" | "Deceased";
};

// Generate deterministic mock data
export const MOCK_PATIENTS: Patient[] = [
    // Stage III (Better survival)
    { id: "PT_01", type: "Gastric", stage: "III", hrd: 45.2, os_months: 24.5, status: "Alive" },
    { id: "PT_03", type: "Gastric", stage: "III", hrd: 32.1, os_months: 36.0, status: "Alive" },
    { id: "PT_05", type: "Gastric", stage: "III", hrd: 28.4, os_months: 48.0, status: "Alive" },
    { id: "PT_07", type: "Gastric", stage: "III", hrd: 55.0, os_months: 12.0, status: "Deceased" },
    { id: "PT_09", type: "Gastric", stage: "III", hrd: 41.2, os_months: 60.0, status: "Alive" },
    { id: "PT_11", type: "Gastric", stage: "III", hrd: 38.9, os_months: 55.0, status: "Alive" },
    { id: "PT_13", type: "Gastric", stage: "III", hrd: 44.5, os_months: 18.2, status: "Deceased" },
    { id: "PT_15", type: "Gastric", stage: "III", hrd: 36.7, os_months: 42.1, status: "Alive" },

    // Stage IV (Worse survival)
    { id: "PT_02", type: "Gastric", stage: "IV", hrd: 12.4, os_months: 8.5, status: "Deceased" },
    { id: "PT_04", type: "Gastric", stage: "IV", hrd: 15.6, os_months: 12.4, status: "Deceased" },
    { id: "PT_06", type: "Gastric", stage: "IV", hrd: 8.2, os_months: 4.1, status: "Deceased" },
    { id: "PT_08", type: "Gastric", stage: "IV", hrd: 22.0, os_months: 18.5, status: "Alive" },
    { id: "PT_10", type: "Gastric", stage: "IV", hrd: 11.5, os_months: 6.2, status: "Deceased" },
    { id: "PT_12", type: "Gastric", stage: "IV", hrd: 9.8, os_months: 14.3, status: "Deceased" },
    { id: "PT_14", type: "Gastric", stage: "IV", hrd: 14.2, os_months: 10.1, status: "Deceased" },
    { id: "PT_16", type: "Gastric", stage: "IV", hrd: 18.5, os_months: 22.0, status: "Alive" },
];

export const MOCK_CODE_SNIPPET = `# Generated by AI Co-Scientist
import pandas as pd
from lifelines import KaplanMeierFitter

# 1. Load Data
df = load_cohort('current_selection')
group_3 = df[df['stage'] == 'III']
group_4 = df[df['stage'] == 'IV']

# 2. Plot Survival
kmf = KaplanMeierFitter()
kmf.fit(group_3['time'], group_3['event'], label='Stage III')
kmf.plot()
kmf.fit(group_4['time'], group_4['event'], label='Stage IV')
kmf.plot()
`
